### ISSUE TITLE
Sample data widget not working - 6/16/18

### ISSUE THREAD

**Issue by uz902a** [ALM-Rangers/Sample-Data-Widget-Extension#12]
I am sorry I made a mistake. I wrote about the sample data not working for VSTS and someone wrote about it already. I just didnt understand how to use it and explain what happened. The error that some one reported earlier is,  "Data Creation didnt finish".  I hope someone can fix? Sorry for a duplicate report.

**Comment by jeffrey-opdam** [comment]
Closing issues, as the project is deprecated
