### ISSUE TITLE
Re-scaffold this project using the extension generator?

### ISSUE THREAD

**Issue by nschonni** [ALM-Rangers/Sample-Data-Widget-Extension#7]
Noticed that at some point a bunch of node_modules and binary stuff got checked in. As I started to clean it up, I thought that maybe it makes more sense to just re-align this repo with https://github.com/ALM-Rangers/generator-vsts-extension rather than just cleaning up the solution.

**Comment by wpschaub** [comment]
@mattias-skold?

**Comment by mattias-skold** [comment]
I'm not over enthusiastic about the idea, but I'm not closing the door entirely either. 
I would like to check the below items before moving forward : 
1) An efficient local development story 
2) Full support for Visual Studio  
3)  WE need to fix the Telemetry Client package before we deploy anything.,..

**Comment by nschonni** [comment]
What does "Full support for Visual Studio" mean to you? 
The main reason I could see for the solution file was for Coded UI tests, but I wasn't sure if the were being used.
