### ISSUE TITLE
Enabling the Sample Data Packages

### ISSUE THREAD

**Issue by nschonni** [ALM-Rangers/Sample-Data-Widget-Extension#9]
Installed 1.3.6 into a TFS 2017 Update 1 server and the following message is shown when viewing the local gallery:
> **Add your own Sample Data Packages**
Currently we have disabled access to the configuration pane due to changes in how widgets handles configuration. We will bring back the capability to have your own custom Sample Data packages as soon as possible

Should this be added back to the README here, or are there plans to add back the functionality?

**Comment by jeffrey-opdam** [comment]
Closing issues, as the project is deprecated

**Comment by nschonni** [comment]
@jeffrey-opdam ok, might be good to mark it as archived then https://help.github.com/en/articles/archiving-repositories
